### ISSUE TITLE
Error at launch 1.19.2

### ISSUE THREAD

**Issue by Fellwing** [ldtteam/Domum-Ornamentum#118]
I've been putting together a modpack of my own (1.19.2) and keep getting t his crash error when trying to launch:
<img width="585" alt="2023-01-05 15_28_30-Felhaven" src="https://user-images.githubusercontent.com/122054738/210874323-15a02b36-7646-4b3e-817c-bee4b5fc7cc5.png">

Text:
15:28:19.717
launcher
main

Exception in thread "main" java.lang.module.ResolutionException: Modules org.yaml.snakeyaml and mcpitanlibarch export package org.yaml.snakeyaml to module domum_ornamentum
	at java.base/java.lang.module.Resolver.resolveFail(Resolver.java:901)
	at java.base/java.lang.module.Resolver.failTwoSuppliers(Resolver.java:815)
	at java.base/java.lang.module.Resolver.checkExportSuppliers(Resolver.java:736)
	at java.base/java.lang.module.Resolver.finish(Resolver.java:380)
	at java.base/java.lang.module.Configuration.<init>(Configuration.java:140)
	at java.base/java.lang.module.Configuration.resolveAndBind(Configuration.java:494)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.ModuleLayerHandler.buildLayer(ModuleLayerHandler.java:75)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.TransformationServicesHandler.buildTransformingClassLoader(TransformationServicesHandler.java:60)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.Launcher.run(Launcher.java:104)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.Launcher.main(Launcher.java:77)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23)
	at cpw.mods.bootstraplauncher@1.1.2/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141)
15:28:19.717
monitor
Process Monitor
Process crashed with exit code 1

Any ideas? I've reinstalled, dug around my appdata folder, reinstalled Java, and nothing. :(

**Comment by marchermans** [comment]
This is not rated to do, but but to mcpitanlibarch. Report it to them.

**Comment by Fellwing** [comment]
> This is not rated to do, but but to mcpitanlibarch. Report it to them.

Thank you! I'll dig into it!
