### ISSUE TITLE
Client crashes because Ambient Oclusion

### ISSUE THREAD

**Issue by ipradasgomez** [ldtteam/Domum-Ornamentum#123]
Time: 2023-01-22 14:09:38
Description: Tesselating block model

com.google.common.util.concurrent.ExecutionError: java.lang.NoSuchMethodError: 'boolean net.minecraft.client.renderer.block.model.BakedQuad.hasAmbientOcclusion()'
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2053) ~[guava-31.0.1-jre.jar%23115!/:?] {}
	at com.google.common.cache.LocalCache.get(LocalCache.java:3966) ~[guava-31.0.1-jre.jar%23115!/:?] {}
	at com.google.common.cache.LocalCache$LocalManualCache.get(LocalCache.java:4863) ~[guava-31.0.1-jre.jar%23115!/:?] {}
	at com.ldtteam.domumornamentum.client.model.baked.MateriallyTexturedBakedModel.getBakedInnerModelFor(MateriallyTexturedBakedModel.java:215) ~[Domum-Ornamentum-Mod-Forge-1.19.2.jar%23270!/:1.19-1.0.75-ALPHA] {re:classloading,pl:rei_plugin_compatibilities:B}
	at com.ldtteam.domumornamentum.client.model.baked.MateriallyTexturedBakedModel.getBakedInnerModelFor(MateriallyTexturedBakedModel.java:209) ~[Domum-Ornamentum-Mod-Forge-1.19.2.jar%23270!/:1.19-1.0.75-ALPHA] {re:classloading,pl:rei_plugin_compatibilities:B}
	at com.ldtteam.domumornamentum.client.model.baked.MateriallyTexturedBakedModel.getQuads(MateriallyTexturedBakedModel.java:96) ~[Domum-Ornamentum-Mod-Forge-1.19.2.jar%23270!/:1.19-1.0.75-ALPHA] {re:classloading,pl:rei_plugin_compatibilities:B}
	at net.minecraft.client.renderer.block.ModelBlockRenderer.renderModelSmooth(ModelBlockRenderer.java:156) ~[client-1.19.2-20220805.130853-srg.jar%23339!/:?] {re:mixin,xf:OptiFine:default,re:classloading,pl:rei_plugin_compatibilities:B,xf:OptiFine:default}
	at net.minecraft.client.renderer.block.ModelBlockRenderer.tesselateBlock(ModelBlockRenderer.java:109) ~[client-1.19.2-20220805.130853-srg.jar%23339!/:?] {re:mixin,xf:OptiFine:default,re:classloading,pl:rei_plugin_compatibilities:B,xf:OptiFine:default}
	at net.minecraft.client.renderer.block.BlockRenderDispatcher.renderBatched(BlockRenderDispatcher.java:90) ~[client-1.19.2-20220805.130853-srg.jar%23339!/:?] {re:classloading,pl:rei_plugin_compatibilities:B,xf:OptiFine:default}
	at net.minecraft.client.renderer.chunk.ChunkRenderDispatcher$RenderChunk$RebuildTask.m_234467_(ChunkRenderDispatcher.java:1065) ~[client-1.19.2-20220805.130853-srg.jar%23339!/:?] {re:classloading,pl:rei_plugin_compatibilities:B,xf:OptiFine:default}
	at net.minecraft.client.renderer.chunk.ChunkRenderDispatcher$RenderChunk$RebuildTask.m_5869_(ChunkRenderDispatcher.java:908) ~[client-1.19.2-20220805.130853-srg.jar%23339!/:?] {re:classloading,pl:rei_plugin_compatibilities:B,xf:OptiFine:default}
	at net.minecraft.client.renderer.chunk.ChunkRenderDispatcher.lambda$runTask$0(ChunkRenderDispatcher.java:195) ~[client-1.19.2-20220805.130853-srg.jar%23339!/:?] {re:classloading,pl:rei_plugin_compatibilities:B,xf:OptiFine:default}
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760) ~[?:?] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {re:computing_frames,pl:rei_plugin_compatibilities:B}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {re:computing_frames,pl:rei_plugin_compatibilities:B}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {}
Caused by: java.lang.NoSuchMethodError: 'boolean net.minecraft.client.renderer.block.model.BakedQuad.hasAmbientOcclusion()'
	at net.minecraftforge.client.model.IQuadTransformer.copy(IQuadTransformer.java:95) ~[forge-1.19.2-43.2.3-universal.jar%23344!/:?] {re:classloading,pl:rei_plugin_compatibilities:B}
	at net.minecraftforge.client.model.IQuadTransformer.process(IQuadTransformer.java:41) ~[forge-1.19.2-43.2.3-universal.jar%23344!/:?] {re:classloading,pl:rei_plugin_compatibilities:B}
	at com.ldtteam.domumornamentum.client.model.baked.RetexturedBakedModelBuilder.lambda$retexture$3(RetexturedBakedModelBuilder.java:164) ~[Domum-Ornamentum-Mod-Forge-1.19.2.jar%23270!/:1.19-1.0.75-ALPHA] {re:classloading,pl:rei_plugin_compatibilities:B}
	at java.util.Optional.map(Optional.java:260) ~[?:?] {re:mixin}
	at com.ldtteam.domumornamentum.client.model.baked.RetexturedBakedModelBuilder.retexture(RetexturedBakedModelBuilder.java:162) ~[Domum-Ornamentum-Mod-Forge-1.19.2.jar%23270!/:1.19-1.0.75-ALPHA] {re:classloading,pl:rei_plugin_compatibilities:B}
	at com.ldtteam.domumornamentum.client.model.baked.RetexturedBakedModelBuilder.lambda$build$0(RetexturedBakedModelBuilder.java:110) ~[Domum-Ornamentum-Mod-Forge-1.19.2.jar%23270!/:1.19-1.0.75-ALPHA] {re:classloading,pl:rei_plugin_compatibilities:B}
	at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?] {re:mixin}
	at com.ldtteam.domumornamentum.client.model.baked.RetexturedBakedModelBuilder.build(RetexturedBakedModelBuilder.java:107) ~[Domum-Ornamentum-Mod-Forge-1.19.2.jar%23270!/:1.19-1.0.75-ALPHA] {re:classloading,pl:rei_plugin_compatibilities:B}
	at com.ldtteam.domumornamentum.client.model.baked.MateriallyTexturedBakedModel.lambda$getBakedInnerModelFor$4(MateriallyTexturedBakedModel.java:225) ~[Domum-Ornamentum-Mod-Forge-1.19.2.jar%23270!/:1.19-1.0.75-ALPHA] {re:classloading,pl:rei_plugin_compatibilities:B}
	at com.google.common.cache.LocalCache$LocalManualCache$1.load(LocalCache.java:4868) ~[guava-31.0.1-jre.jar%23115!/:?] {}
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3533) ~[guava-31.0.1-jre.jar%23115!/:?] {}
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2282) ~[guava-31.0.1-jre.jar%23115!/:?] {}
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2159) ~[guava-31.0.1-jre.jar%23115!/:?] {}
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2049) ~[guava-31.0.1-jre.jar%23115!/:?] {}
	... 18 more

**Comment by MotionlessTrain** [comment]
Don't use optifine in 1.19. If you want to use shaders, use rubidium and oculus instead
