### ISSUE TITLE
Server stops with error message: Encountered an unexpected exception

### ISSUE THREAD

**Issue by JonahAW** [ldtteam/Domum-Ornamentum#132]
[Server thread/ERROR] [minecraft/MinecraftServer]: Encountered an unexpected exception
java.lang.ClassCastException: class com.ldtteam.domumornamentum.entity.block.MateriallyTexturedBlockEntity cannot be cast to class net.minecraft.world.level.block.entity.ChestBlockEntity (com.ldtteam.domumornamentum.entity.block.MateriallyTexturedBlockEntity is in module domum_ornamentum@1.18.2-1.0.50-ALPHA of loader 'TRANSFORMER' @759a678a; net.minecraft.world.level.block.entity.ChestBlockEntity is in module minecraft@1.18.2 of loader 'TRANSFORMER' @759a678a)
        at org.bukkit.craftbukkit.v1_18_R2.block.CraftBlockStates$BlockEntityStateFactory.createBlockState(CraftBlockStates.java:64) ~[forge-1.18.2-40.2.1-universal.jar%2394!/:?] {re:classloading}
        at org.bukkit.craftbukkit.v1_18_R2.block.CraftBlockStates$BlockEntityStateFactory.createBlockState(CraftBlockStates.java:56) ~[forge-1.18.2-40.2.1-universal.jar%2394!/:?] {re:classloading}
        at org.bukkit.craftbukkit.v1_18_R2.block.CraftBlockStates$BlockEntityStateFactory.createBlockState(CraftBlockStates.java:38) ~[forge-1.18.2-40.2.1-universal.jar%2394!/:?] {re:classloading}
        at org.bukkit.craftbukkit.v1_18_R2.block.CraftBlockStates.getBlockState(CraftBlockStates.java:339) ~[forge-1.18.2-40.2.1-universal.jar%2394!/:?] {re:classloading}
        at org.bukkit.craftbukkit.v1_18_R2.block.CraftBlockStates.getBlockState(CraftBlockStates.java:302) ~[forge-1.18.2-40.2.1-universal.jar%2394!/:?] {re:classloading}
        at org.bukkit.craftbukkit.v1_18_R2.block.CraftBlock.getState(CraftBlock.java:321) ~[forge-1.18.2-40.2.1-universal.jar%2394!/:?] {re:classloading}
        at org.bukkit.craftbukkit.v1_18_R2.CraftChunk.getTileEntities(CraftChunk.java:189) ~[forge-1.18.2-40.2.1-universal.jar%2394!/:7e29f765-296df566-9fb885e8] {re:classloading}
        at co.aikar.timings.TimingHistory$2.apply(TimingHistory.java:123) ~[forge-1.18.2-40.2.1-universal.jar%2394!/:?] {re:classloading}
        at co.aikar.timings.TimingHistory$2.apply(TimingHistory.java:105) ~[forge-1.18.2-40.2.1-universal.jar%2394!/:?] {re:classloading}
        at co.aikar.util.JSONUtil.toObjectMapper(JSONUtil.java:119) ~[forge-1.18.2-40.2.1-universal.jar%2394!/:?] {re:classloading}
        at co.aikar.timings.TimingHistory.<init>(TimingHistory.java:105) ~[forge-1.18.2-40.2.1-universal.jar%2394!/:?] {re:classloading}
        at co.aikar.timings.FullServerTickHandler.stopTiming(FullServerTickHandler.java:76) ~[forge-1.18.2-40.2.1-universal.jar%2394!/:?] {re:classloading}
        at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:1127) ~[server-1.18.2-20220404.173914-srg.jar%2389!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_minecraftserverclass,re:classloading,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_minecraftserverclass,pl:mixin:APP:crafttweaker.mixins.json:common.access.server.AccessMinecraftServer,pl:mixin:A,re:mixin,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_minecraftserverclass}
        at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:881) ~[server-1.18.2-20220404.173914-srg.jar%2389!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_minecraftserverclass,re:classloading,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_minecraftserverclass,pl:mixin:APP:crafttweaker.mixins.json:common.access.server.AccessMinecraftServer,pl:mixin:A,re:mixin,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_minecraftserverclass}
        at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:259) ~[server-1.18.2-20220404.173914-srg.jar%2389!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_minecraftserverclass,re:classloading,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_minecraftserverclass,pl:mixin:APP:crafttweaker.mixins.json:common.access.server.AccessMinecraftServer,pl:mixin:A,re:mixin,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_minecraftserverclass}
        at java.lang.Thread.run(Thread.java:833) [?:?] {re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin}
[16:00:34] [Server thread/FATAL] [ne.mi.co.ForgeMod/]: Preparing crash report with UUID 6d1c7c6c-283e-4258-87d7-8ba642c60fbf

I don´t know where the error lies. Can you maybe find one. The server ran without problems for many hours. Right now I am upgrading the town hall to level 3 in MineColonies and at 90% the server crashes. Is there a solution? I am using a Magma type server.

**Comment by Thodor12** [comment]
Next time, don't upload logs here, put them in a [gist](https://gist.github.com/).
I don't see how this can occur normally, the server wants to have a Domum block somewhere, but it's reading a chest block.
I am also noticing references to `bukkit` in your server, what Forge version are you using?

**Comment by marchermans** [comment]
This is running on an unsupported server system.
Closing.

**Comment by xan1mple** [comment]
dr marchermans ,cant this problem be solved?this guy has the same problem as me,he is running the server on Magma (forgemods+plugins).
