### ISSUE TITLE
Double-slab breaking causes UI glitch and crash

### ISSUE THREAD

**Issue by vgrynch** [ldtteam/Domum-Ornamentum#172]
(Minecraft 1.19.2, Domum Ornamentum version: domum_ornamentum-1.19-1.0.111-BETA-universal)

Client crash happens (repeatedly multiple times until the client logs out from the server and closes automatically) - when trying to break the custom double-slab created with architectury cutter (see logs below).

The behavior observed is as follows:
- Craft slab with architectury cutter using 
- Place 2 slabs one on top of another to create a double-slab block
- Break it with the Netherite pickaxe (unenchanted)
- Oak planks block appears in place of it. At this very moment, client-side crashes start to spam the log.  - Quickly breaking that oak planks block allows client to function further.
- You can also try to quickly teleport somewhere and back - the oak planks block appears for 1s or so and then disappears due to chunk updating after teleporting.
- If do nothing and wait a bit, the client disconnects from the server and exits to the loader screen (because of too many repeated crashes.)

It looks like a bad chunk update data or so.
I'm using a lot of mods, so might be conflicting with something, though it looks to me like some generic glitch.

What I would recommend is trying to add an additional guard check to prevent crashes like these.
At my side, of course, I will try to figure out why chunk updates are not coming through completely and what mods might influence this. (I would appreciate any recommendations here...)

```
[25Aug2023 21:30:46.754] [Render thread/ERROR] [com.ldtteam.domumornamentum.client.model.baked.MateriallyTexturedBakedModel/]: Failed to build baked materially textured model for: Block{domum_ornamentum:vanilla_slab_compat}[type=double,waterlogged=false] MaterialTextureData{texturedComponents={minecraft:block/oak_planks=Block{domum_ornamentum:orange_brick_extra}}}
com.google.common.util.concurrent.UncheckedExecutionException: java.lang.NullPointerException: Cannot invoke "net.minecraft.client.renderer.RenderType.getChunkLayerId()" because "renderType" is null
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2055) ~[guava-31.0.1-jre.jar%23121!/:?]
	at com.google.common.cache.LocalCache.get(LocalCache.java:3966) ~[guava-31.0.1-jre.jar%23121!/:?]
	at com.google.common.cache.LocalCache$LocalManualCache.get(LocalCache.java:4863) ~[guava-31.0.1-jre.jar%23121!/:?]
	at com.ldtteam.domumornamentum.client.model.baked.MateriallyTexturedBakedModel.getBakedInnerModelFor(MateriallyTexturedBakedModel.java:215) ~[domum_ornamentum-1.19-1.0.111-BETA-universal.jar%23449!/:1.19-1.0.111-BETA]
	at com.ldtteam.domumornamentum.client.model.baked.MateriallyTexturedBakedModel.getBakedInnerModelFor(MateriallyTexturedBakedModel.java:209) ~[domum_ornamentum-1.19-1.0.111-BETA-universal.jar%23449!/:1.19-1.0.111-BETA]
	at com.ldtteam.domumornamentum.client.model.baked.MateriallyTexturedBakedModel.getQuads(MateriallyTexturedBakedModel.java:96) ~[domum_ornamentum-1.19-1.0.111-BETA-universal.jar%23449!/:1.19-1.0.111-BETA]
	at net.minecraft.client.renderer.block.ModelBlockRenderer.tesselateWithAO(ModelBlockRenderer.java:84) ~[client-1.19.2-20220805.130853-srg.jar%23601!/:?]
	at net.minecraftforge.client.model.lighting.ForgeModelBlockRenderer.tesselateWithAO(ForgeModelBlockRenderer.java:65) ~[forge-1.19.2-43.2.21-universal.jar%23606!/:?]
	at net.minecraft.client.renderer.block.ModelBlockRenderer.tesselateBlock(ModelBlockRenderer.java:58) ~[client-1.19.2-20220805.130853-srg.jar%23601!/:?]
	at net.minecraft.client.renderer.block.ModelBlockRenderer.tesselateBlock(ModelBlockRenderer.java:48) ~[client-1.19.2-20220805.130853-srg.jar%23601!/:?]
	at net.minecraft.client.renderer.block.BlockRenderDispatcher.renderBreakingTexture(BlockRenderDispatcher.java:56) ~[client-1.19.2-20220805.130853-srg.jar%23601!/:?]
	at net.minecraft.client.renderer.LevelRenderer.m_109599_(LevelRenderer.java:1313) ~[client-1.19.2-20220805.130853-srg.jar%23601!/:?]
	at net.minecraft.client.renderer.GameRenderer.m_109089_(GameRenderer.java:1068) ~[client-1.19.2-20220805.130853-srg.jar%23601!/:?]
	at net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:840) ~[client-1.19.2-20220805.130853-srg.jar%23601!/:?]
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1115) ~[client-1.19.2-20220805.130853-srg.jar%23601!/:?]
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:700) ~[client-1.19.2-20220805.130853-srg.jar%23601!/:?]
	at net.minecraft.client.main.Main.m_239872_(Main.java:212) ~[client-1.19.2-20220805.130853-srg.jar%23601!/:?]
	at net.minecraft.client.main.Main.main(Main.java:51) ~[client-1.19.2-20220805.130853-srg.jar%23601!/:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:27) ~[fmlloader-1.19.2-43.2.21.jar%23101!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) [modlauncher-10.0.8.jar%2388!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-10.0.8.jar%2388!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-10.0.8.jar%2388!/:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-10.0.8.jar%2388!/:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-10.0.8.jar%2388!/:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-10.0.8.jar%2388!/:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-10.0.8.jar%2388!/:?]
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) [bootstraplauncher-1.1.2.jar:?]
Caused by: java.lang.NullPointerException: Cannot invoke "net.minecraft.client.renderer.RenderType.getChunkLayerId()" because "renderType" is null
	at net.minecraftforge.client.ChunkRenderTypeSet.contains(ChunkRenderTypeSet.java:124) ~[forge-1.19.2-43.2.21-universal.jar%23606!/:?]
	at com.ldtteam.domumornamentum.client.model.baked.RetexturedBakedModelBuilder.with(RetexturedBakedModelBuilder.java:74) ~[domum_ornamentum-1.19-1.0.111-BETA-universal.jar%23449!/:1.19-1.0.111-BETA]
	at java.util.HashMap.forEach(HashMap.java:1421) ~[?:?]
	at com.ldtteam.domumornamentum.client.model.baked.MateriallyTexturedBakedModel.lambda$getBakedInnerModelFor$4(MateriallyTexturedBakedModel.java:223) ~[domum_ornamentum-1.19-1.0.111-BETA-universal.jar%23449!/:1.19-1.0.111-BETA]
	at com.google.common.cache.LocalCache$LocalManualCache$1.load(LocalCache.java:4868) ~[guava-31.0.1-jre.jar%23121!/:?]
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3533) ~[guava-31.0.1-jre.jar%23121!/:?]
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2282) ~[guava-31.0.1-jre.jar%23121!/:?]
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2159) ~[guava-31.0.1-jre.jar%23121!/:?]
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2049) ~[guava-31.0.1-jre.jar%23121!/:?]
	... 30 more
[25Aug2023 21:30:46.758] [Render thread/ERROR] [com.ldtteam.domumornamentum.client.model.baked.MateriallyTexturedBakedModel/]: Failed to build baked materially textured model for: Block{domum_ornamentum:vanilla_slab_compat}[type=double,waterlogged=false] MaterialTextureData{texturedComponents={minecraft:block/oak_planks=Block{domum_ornamentum:orange_brick_extra}}}
com.google.common.util.concurrent.UncheckedExecutionException: java.lang.NullPointerException: Cannot invoke "net.minecraft.client.renderer.RenderType.getChunkLayerId()" because "renderType" is null
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2055) ~[guava-31.0.1-jre.jar%23121!/:?]
	at com.google.common.cache.LocalCache.get(LocalCache.java:3966) ~[guava-31.0.1-jre.jar%23121!/:?]
	at com.google.common.cache.LocalCache$LocalManualCache.get(LocalCache.java:4863) ~[guava-31.0.1-jre.jar%23121!/:?]
	at com.ldtteam.domumornamentum.client.model.baked.MateriallyTexturedBakedModel.getBakedInnerModelFor(MateriallyTexturedBakedModel.java:215) ~[domum_ornamentum-1.19-1.0.111-BETA-universal.jar%23449!/:1.19-1.0.111-BETA]
	at com.ldtteam.domumornamentum.client.model.baked.MateriallyTexturedBakedModel.getBakedInnerModelFor(MateriallyTexturedBakedModel.java:209) ~[domum_ornamentum-1.19-1.0.111-BETA-universal.jar%23449!/:1.19-1.0.111-BETA]
	at com.ldtteam.domumornamentum.client.model.baked.MateriallyTexturedBakedModel.getQuads(MateriallyTexturedBakedModel.java:96) ~[domum_ornamentum-1.19-1.0.111-BETA-universal.jar%23449!/:1.19-1.0.111-BETA]
	at net.minecraft.client.renderer.block.ModelBlockRenderer.tesselateWithAO(ModelBlockRenderer.java:84) ~[client-1.19.2-20220805.130853-srg.jar%23601!/:?]
	at net.minecraftforge.client.model.lighting.ForgeModelBlockRenderer.tesselateWithAO(ForgeModelBlockRenderer.java:65) ~[forge-1.19.2-43.2.21-universal.jar%23606!/:?]
	at net.minecraft.client.renderer.block.ModelBlockRenderer.tesselateBlock(ModelBlockRenderer.java:58) ~[client-1.19.2-20220805.130853-srg.jar%23601!/:?]
	at net.minecraft.client.renderer.block.ModelBlockRenderer.tesselateBlock(ModelBlockRenderer.java:48) ~[client-1.19.2-20220805.130853-srg.jar%23601!/:?]
	at net.minecraft.client.renderer.block.BlockRenderDispatcher.renderBreakingTexture(BlockRenderDispatcher.java:56) ~[client-1.19.2-20220805.130853-srg.jar%23601!/:?]
	at net.minecraft.client.renderer.LevelRenderer.m_109599_(LevelRenderer.java:1313) ~[client-1.19.2-20220805.130853-srg.jar%23601!/:?]
	at net.minecraft.client.renderer.GameRenderer.m_109089_(GameRenderer.java:1068) ~[client-1.19.2-20220805.130853-srg.jar%23601!/:?]
	at net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:840) ~[client-1.19.2-20220805.130853-srg.jar%23601!/:?]
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1115) ~[client-1.19.2-20220805.130853-srg.jar%23601!/:?]
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:700) ~[client-1.19.2-20220805.130853-srg.jar%23601!/:?]
	at net.minecraft.client.main.Main.m_239872_(Main.java:212) ~[client-1.19.2-20220805.130853-srg.jar%23601!/:?]
	at net.minecraft.client.main.Main.main(Main.java:51) ~[client-1.19.2-20220805.130853-srg.jar%23601!/:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:27) ~[fmlloader-1.19.2-43.2.21.jar%23101!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) [modlauncher-10.0.8.jar%2388!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-10.0.8.jar%2388!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-10.0.8.jar%2388!/:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-10.0.8.jar%2388!/:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-10.0.8.jar%2388!/:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-10.0.8.jar%2388!/:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-10.0.8.jar%2388!/:?]
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) [bootstraplauncher-1.1.2.jar:?]
Caused by: java.lang.NullPointerException: Cannot invoke "net.minecraft.client.renderer.RenderType.getChunkLayerId()" because "renderType" is null
	at net.minecraftforge.client.ChunkRenderTypeSet.contains(ChunkRenderTypeSet.java:124) ~[forge-1.19.2-43.2.21-universal.jar%23606!/:?]
	at com.ldtteam.domumornamentum.client.model.baked.RetexturedBakedModelBuilder.with(RetexturedBakedModelBuilder.java:74) ~[domum_ornamentum-1.19-1.0.111-BETA-universal.jar%23449!/:1.19-1.0.111-BETA]
	at java.util.HashMap.forEach(HashMap.java:1421) ~[?:?]
	at com.ldtteam.domumornamentum.client.model.baked.MateriallyTexturedBakedModel.lambda$getBakedInnerModelFor$4(MateriallyTexturedBakedModel.java:223) ~[domum_ornamentum-1.19-1.0.111-BETA-universal.jar%23449!/:1.19-1.0.111-BETA]
	at com.google.common.cache.LocalCache$LocalManualCache$1.load(LocalCache.java:4868) ~[guava-31.0.1-jre.jar%23121!/:?]
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3533) ~[guava-31.0.1-jre.jar%23121!/:?]
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2282) ~[guava-31.0.1-jre.jar%23121!/:?]
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2159) ~[guava-31.0.1-jre.jar%23121!/:?]
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2049) ~[guava-31.0.1-jre.jar%23121!/:?]
	... 30 more
```

**Comment by Raycoms** [comment]
This should be fixed in the newest, can you test that?

**Comment by vgrynch** [comment]
@Raycoms, it does not crash, but 2 slabs after breaking such double-slab block are not returned at all.
