### ISSUE TITLE
ClassNotFoundException

### ISSUE THREAD

**Issue by autonad** [ldtteam/Domum-Ornamentum#20]
Now I'm having a problem with class not found exception.

I don't know if this relates to this mod issue or something.. Also I have little knowledge about this. 

So at that time, I'm done with creating modpack. So I click play game and wait for a bit on the loading screen. When the bar is full and disappear, my game crashed.

Here's my crash log.

```
---- Minecraft Crash Report ----
// Don't do that.

Time: 1/1/22, 4:57 PM
Description: Mod loading error has occurred

java.lang.Exception: Mod Loading has failed
	at net.minecraftforge.fmllegacy.CrashReportExtender.dumpModLoadingCrashReport(CrashReportExtender.java:69) ~[forge-1.17.1-37.1.1-universal.jar%2396!:?] {re:classloading}
	at net.minecraftforge.fmlclient.ClientModLoader.completeModLoading(ClientModLoader.java:185) ~[forge-1.17.1-37.1.1-universal.jar%2396!:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.lambda$new$1(Minecraft.java:555) ~[client-1.17.1-20210706.113038-srg.jar%2392!:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:betterthirdperson.mixins.json:MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.Util.m_137521_(Util.java:507) ~[client-1.17.1-20210706.113038-srg.jar%2392!:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.client.Minecraft.lambda$new$2(Minecraft.java:549) ~[client-1.17.1-20210706.113038-srg.jar%2392!:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:betterthirdperson.mixins.json:MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.screens.LoadingOverlay.m_6305_(LoadingOverlay.java:196) ~[client-1.17.1-20210706.113038-srg.jar%2392!:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:1252) ~[client-1.17.1-20210706.113038-srg.jar%2392!:?] {re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1039) ~[client-1.17.1-20210706.113038-srg.jar%2392!:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:betterthirdperson.mixins.json:MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:659) ~[client-1.17.1-20210706.113038-srg.jar%2392!:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:betterthirdperson.mixins.json:MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:186) ~[client-1.17.1-20210706.113038-srg.jar%2392!:?] {re:classloading,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:45) ~[fmlloader-1.17.1-37.1.1.jar%2323!:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-9.0.7.jar%235!:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-9.0.7.jar%235!:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-9.0.7.jar%235!:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-9.0.7.jar%235!:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-9.0.7.jar%235!:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-9.0.7.jar%235!:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-9.0.7.jar%235!:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:90) [bootstraplauncher-0.1.17.jar:?] {}


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:135) ~[securejarhandler-0.9.54.jar:?] {}
-- MOD domum_ornamentum --
Details:
	Caused by 0: java.lang.RuntimeException: java.lang.ClassNotFoundException: com.ldtteam.domumornamentum.client.event.handlers.ClientTickEventHandler
		at net.minecraftforge.fml.javafmlmod.AutomaticEventSubscriber.lambda$inject$6(AutomaticEventSubscriber.java:80) ~[javafmllanguage-1.17.1-37.1.1.jar%2394!:?] {}
		at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?] {re:computing_frames}
		at net.minecraftforge.fml.javafmlmod.AutomaticEventSubscriber.inject(AutomaticEventSubscriber.java:62) ~[javafmllanguage-1.17.1-37.1.1.jar%2394!:?] {}
		at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:91) ~[javafmllanguage-1.17.1-37.1.1.jar%2394!:?] {}
		at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:120) ~[fmlcore-1.17.1-37.1.1.jar%2393!:?] {}
		at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1800) ~[?:?] {}
		at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1792) ~[?:?] {}
		at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:295) ~[?:?] {}
		at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1016) ~[?:?] {}
		at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1665) ~[?:?] {re:computing_frames}
		at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1598) ~[?:?] {re:computing_frames}
		at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183) ~[?:?] {}

	Mod File: domum_ornamentum-1.17.1-1.0.27-ALPHA-universal.jar
	Failure message: Domum Ornamentum (domum_ornamentum) has failed to load correctly
		java.lang.RuntimeException: java.lang.ClassNotFoundException: com.ldtteam.domumornamentum.client.event.handlers.ClientTickEventHandler
	Mod Version: 1.17.1-1.0.27-ALPHA
	Mod Issue URL: NOT PROVIDED
	Exception message: java.lang.ClassNotFoundException: com.ldtteam.domumornamentum.client.event.handlers.ClientTickEventHandler
Stacktrace:
	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:135) ~[securejarhandler-0.9.54.jar:?] {}
	at java.lang.ClassLoader.loadClass(ClassLoader.java:519) ~[?:?] {}
	at java.lang.Class.forName0(Native Method) ~[?:?] {re:mixin}
	at java.lang.Class.forName(Class.java:466) ~[?:?] {re:mixin}
	at net.minecraftforge.fml.javafmlmod.AutomaticEventSubscriber.lambda$inject$6(AutomaticEventSubscriber.java:75) ~[javafmllanguage-1.17.1-37.1.1.jar%2394!:?] {}
	at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?] {re:computing_frames}
	at net.minecraftforge.fml.javafmlmod.AutomaticEventSubscriber.inject(AutomaticEventSubscriber.java:62) ~[javafmllanguage-1.17.1-37.1.1.jar%2394!:?] {}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:91) ~[javafmllanguage-1.17.1-37.1.1.jar%2394!:?] {}
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:120) ~[fmlcore-1.17.1-37.1.1.jar%2393!:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1800) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1792) ~[?:?] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:295) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1016) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1665) ~[?:?] {re:computing_frames}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1598) ~[?:?] {re:computing_frames}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183) ~[?:?] {}


-- System Details --
Details:
	Minecraft Version: 1.17.1
	Minecraft Version ID: 1.17.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 16.0.1, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 629399552 bytes (600 MiB) / 1841299456 bytes (1756 MiB) up to 5301600256 bytes (5056 MiB)
	CPUs: 4
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Phenom(tm) II X4 840 Processor
	Identifier: AuthenticAMD Family 16 Model 5 Stepping 3
	Microarchitecture: K10
	Frequency (GHz): 3.22
	Number of physical packages: 1
	Number of physical CPUs: 4
	Number of logical CPUs: 4
	Graphics card #0 name: NVIDIA GeForce GTX 750
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 1024.00
	Graphics card #0 deviceId: 0x1381
	Graphics card #0 versionInfo: DriverVersion=30.0.14.9676
	Memory slot #0 capacity (MB): 4096.00
	Memory slot #0 clockSpeed (GHz): 0.53
	Memory slot #0 type: Other
	Memory slot #1 capacity (MB): 4096.00
	Memory slot #1 clockSpeed (GHz): 0.53
	Memory slot #1 type: Other
	Virtual memory max (MB): 17715.27
	Virtual memory used (MB): 11929.52
	Swap memory total (MB): 9524.03
	Swap memory used (MB): 1133.26
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx5056m -Xms256m
	OptiFine Version: OptiFine_1.17.1_HD_U_H1
	OptiFine Build: 20211104-012451
	Render Distance Chunks: 10
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: (internal)
	OpenGlVersion: 3.2.0 NVIDIA 496.76
	OpenGlRenderer: NVIDIA GeForce GTX 750/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 4
	ModLauncher: 9.0.7+91+master.8569cdf
	ModLauncher launch target: forgeclient
	ModLauncher naming: srg
	ModLauncher services: 
		 mixin PLUGINSERVICE 
		 eventbus PLUGINSERVICE 
		 object_holder_definalize PLUGINSERVICE 
		 runtime_enum_extender PLUGINSERVICE 
		 capability_token_subclass PLUGINSERVICE 
		 capability_inject_definalize PLUGINSERVICE 
		 accesstransformer PLUGINSERVICE 
		 runtimedistcleaner PLUGINSERVICE 
		 mixin TRANSFORMATIONSERVICE 
		 OptiFine TRANSFORMATIONSERVICE 
		 fml TRANSFORMATIONSERVICE 
	FML Language Providers: 
		minecraft@1.0
		javafml@null
	Mod List: 
		client-1.17.1-20210706.113038-srg.jar             |Minecraft                     |minecraft                     |1.17.1              |COMMON_SET|Manifest: a1:d4:5e:04:4f:d3:d6:e0:7b:37:97:cf:77:b0:de:ad:4a:47:ce:8c:96:49:5f:0a:cf:8c:ae:b2:6d:4b:8a:3f
		morevillagers-FORGE-1.17-2.1.1.jar                |More Villagers                |morevillagers                 |2.1.1               |COMMON_SET|Manifest: NOSIGNATURE
		MouseTweaks-forge-mc1.17.1-2.15.jar               |Mouse Tweaks                  |mousetweaks                   |2.15                |COMMON_SET|Manifest: NOSIGNATURE
		netherportalspread_1.17.1-5.6.jar                 |Nether Portal Spread          |netherportalspread            |5.6                 |COMMON_SET|Manifest: NOSIGNATURE
		BiomesOPlenty-1.17.1-14.0.0.36-universal.jar      |Biomes O' Plenty              |biomesoplenty                 |1.17.1-14.0.0.36    |COMMON_SET|Manifest: NOSIGNATURE
		jei-1.17.1-8.3.0.49.jar                           |Just Enough Items             |jei                           |8.3.0.49            |COMMON_SET|Manifest: NOSIGNATURE
		domum_ornamentum-1.17.1-1.0.27-ALPHA-universal.jar|Domum Ornamentum              |domum_ornamentum              |1.17.1-1.0.27-ALPHA |ERROR     |Manifest: NOSIGNATURE
		curios-forge-1.17.1-5.0.2.6.jar                   |Curios API                    |curios                        |1.17.1-5.0.2.6      |COMMON_SET|Manifest: NOSIGNATURE
		Patchouli-1.17.1-57.jar                           |Patchouli                     |patchouli                     |1.17.1-57           |COMMON_SET|Manifest: NOSIGNATURE
		blockui-1.17.1-0.0.20-ALPHA.jar                   |UI Library Mod                |blockui                       |1.17.1-0.0.20-ALPHA |COMMON_SET|Manifest: NOSIGNATURE
		waystones-8.2.0+0.jar                             |Waystones                     |waystones                     |8.2.0+0             |COMMON_SET|Manifest: NOSIGNATURE
		collective-1.17.1-3.8.jar                         |Collective                    |collective                    |3.8                 |COMMON_SET|Manifest: NOSIGNATURE
		Clumps-forge-1.17.1-7.0.10.jar                    |Clumps                        |clumps                        |7.0.10              |COMMON_SET|Manifest: NOSIGNATURE
		journeymap-1.17.1-5.7.3.jar                       |Journeymap                    |journeymap                    |5.7.3               |COMMON_SET|Manifest: NOSIGNATURE
		FastWorkbench-1.17.1-5.0.1.jar                    |Fast Workbench                |fastbench                     |5.0.1               |COMMON_SET|Manifest: NOSIGNATURE
		Controlling-forge-1.17.1-8.0.11.jar               |Controlling                   |controlling                   |8.0.11              |COMMON_SET|Manifest: NOSIGNATURE
		Placebo-1.17.1-5.0.2.jar                          |Placebo                       |placebo                       |5.0.2               |COMMON_SET|Manifest: NOSIGNATURE
		comforts-forge-1.17.1-5.0.0.1.jar                 |Comforts                      |comforts                      |1.17.1-5.0.0.1      |COMMON_SET|Manifest: NOSIGNATURE
		TravelersBackpack-1.17.1-6.0.5.jar                |Traveler's Backpack           |travelersbackpack             |6.0.5               |COMMON_SET|Manifest: NOSIGNATURE
		artifacts-1.17.1-3.0.2.jar                        |Artifacts                     |artifacts                     |1.17.1-3.0.2        |COMMON_SET|Manifest: NOSIGNATURE
		BetterThirdPerson-Forge-1.17.1-1.5.2.jar          |Better Third Person           |betterthirdperson             |1.5.2               |COMMON_SET|Manifest: NOSIGNATURE
		InventoryHud_[1.17.1].forge-3.4.1.jar             |Inventory HUD+(Forge edition) |inventoryhud                  |3.4.1               |COMMON_SET|Manifest: NOSIGNATURE
		DungeonCrawl-1.17.1-2.3.5.jar                     |Dungeon Crawl                 |dungeoncrawl                  |2.3.5               |COMMON_SET|Manifest: NOSIGNATURE
		structurize-1.17.1-1.0.311-BETA.jar               |Structurize                   |structurize                   |1.17.1-1.0.311-BETA |COMMON_SET|Manifest: NOSIGNATURE
		multi-piston-1.17.1-1.2.1-ALPHA.jar               |Multi-Piston                  |multipiston                   |1.17.1-1.2.1-ALPHA  |COMMON_SET|Manifest: NOSIGNATURE
		Bookshelf-Forge-1.17.1-11.0.3.jar                 |Bookshelf                     |bookshelf                     |11.0.3              |COMMON_SET|Manifest: eb:c4:b1:67:8b:f9:0c:db:dc:4f:01:b1:8e:61:64:39:4c:10:85:0b:a6:c4:c7:48:f0:fa:95:f2:cb:08:3a:e5
		guardvillagers-1.17.1.1.3.4.jar                   |Guard Villagers               |guardvillagers                |1.3.4               |COMMON_SET|Manifest: NOSIGNATURE
		FastFurnace-1.17.1-5.0.0.jar                      |FastFurnace                   |fastfurnace                   |5.0.0               |COMMON_SET|Manifest: NOSIGNATURE
		AI-Improvements-1.17.1-0.4.0.jar                  |AI-Improvements               |aiimprovements                |0.4.0               |COMMON_SET|Manifest: NOSIGNATURE
		balm-1.8.2+0.jar                                  |Balm                          |balm                          |1.8.2+0             |COMMON_SET|Manifest: NOSIGNATURE
		enhancedcelestials-2.0.9-1.17.1.jar               |Enhanced Celestials           |enhancedcelestials            |2.0.9               |COMMON_SET|Manifest: NOSIGNATURE
		JustEnoughResources-1.17.1-0.13.1.134.jar         |Just Enough Resources         |jeresources                   |0.13.1.134          |COMMON_SET|Manifest: NOSIGNATURE
		forge-1.17.1-37.1.1-universal.jar                 |Forge                         |forge                         |37.1.1              |COMMON_SET|Manifest: 22:af:21:d8:19:82:7f:93:94:fe:2b:ac:b7:e4:41:57:68:39:87:b1:a7:5c:c6:44:f9:25:74:21:14:f5:0d:90
		appleskin-forge-mc1.17.1-2.2.0.jar                |AppleSkin                     |appleskin                     |2.2.0               |COMMON_SET|Manifest: NOSIGNATURE
		FastLeafDecay-26.1.jar                            |FastLeafDecay                 |fastleafdecay                 |26.1                |COMMON_SET|Manifest: NOSIGNATURE
		expandability-4.0.2-forge.jar                     |ExpandAbility                 |expandability                 |4.0.2               |COMMON_SET|Manifest: NOSIGNATURE
		ironchest-1.17.1-12.0.2.jar                       |Iron Chests                   |ironchest                     |1.17.1-12.0.2       |COMMON_SET|Manifest: NOSIGNATURE
		corpse-1.17.1-1.0.5.jar                           |Corpse                        |corpse                        |1.17.1-1.0.5        |COMMON_SET|Manifest: NOSIGNATURE
		BetterAdvancements-1.17.1-0.1.2.119.jar           |Better Advancements           |betteradvancements            |0.1.2.119           |COMMON_SET|Manifest: NOSIGNATURE
	Crash Report UUID: 00857d69-ce8d-405c-8dc4-c5858ad7e21a
	FML: 37.1
	Forge: net.minecraftforge:37.1.1

```

**Comment by marchermans** [comment]
I need the entire log file please.

**Comment by autonad** [comment]
Oh, um.. I fixed it long ago. I realized that all I needed to do is to reinstall it correctly without changing version while it's still on my mod list. (I can't explain very well, haha. but thank you!)
