### ISSUE TITLE
Server crash and spam getDOSoundType

### ISSUE THREAD

**Issue by DragonMotion** [ldtteam/Domum-Ornamentum#232]
For some unknown reason, the server crashed during the game. Now, when a player joins, there is a constant crash. The error indicates a Domum-Ornamentum. Perhaps the error started to occur when I set the minimum number of stone slabs to be stored in a warehouse in minecolonies.

Spam error: 
```
at com.ldtteam.domumornamentum.block.decorative.TimberFrameBlock.getSoundType(TimberFrameBlock.java:216) ~[domum_ornamentum-1.20-1.0.170-BETA-universal.jar%23394!/:1.20-1.0.170-BETA]
at com.ldtteam.domumornamentum.block.IMateriallyTexturedBlock.getDOSoundType(IMateriallyTexturedBlock.java:138) ~[domum_ornamentum-1.20-1.0.170-BETA-universal.jar%23394!/:1.20-1.0.170-BETA]
```

https://gist.github.com/DragonMotion/ee4ea2d9925e181842a86bfa74d892ea

[latest.log](https://github.com/ldtteam/Domum-Ornamentum/files/14719527/latest.log)

- domum_ornamentum-1.20-1.0.172-BETA-universal.jar

**Comment by Raycoms** [comment]
fixed, thanks for reporting
